version: '3.8'  # Define the version of Docker Compose

services:
  web:
    build: .  # Build the image from the current directory (where Dockerfile is located)
    ports:
      - "5000:5000"  # Map port 5000 on the host to port 5000 in the container
    volumes:
      - .:/app  # Mount the current directory into the /app directory inside the container
    environment:
      FLASK_ENV: development  # Set environment variable for Flask
    restart: always
